export { default as Signup } from "./Signup/Signup";
export { default as Home } from "./Home/Home";
export { default as Page1 } from "./Page1/Page1";
export { default as Page2 } from "./Page2/Page2";
export { default as Page3 } from "./Page3/Page3";
export { default as Page4 } from "./Page4/Page4";
export { default as Page5 } from "./Page5/Page5";
export { default as Page6 } from "./Page6/Page6";
export { default as Page7 } from "./Page7/Page7";
